import api from './client';
export const getPlates = (params) => api.get('/plates', { params });
export const getPlateById = (id) => api.get(`/plates/${id}`);
export const createPlate = (data) => api.post('/plates', data);
export const getPlateCategories = () => api.get('/plates/categories');
export const getPlateJurisdictions = () => api.get('/plates/jurisdictions');
export const toggleWatch = (id) => api.post(`/plates/${id}/watch`);
export const makeOffer = (id, data) => api.post(`/plates/${id}/offers`, data);
export const getOffers = (id) => api.get(`/plates/${id}/offers`);
export const respondToOffer = (id, status) => api.patch(`/plates/offers/${id}`, { status });
