import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { useCars } from '../hooks/useCars';
import CarCard from '../components/CarCard';
import CarFilters from '../components/CarFilters';
import Pagination from '../components/Pagination';
import { getCarById, getCars } from '../api/cars';
import { fmtPrice } from '../utils/format';
const BrowsePage = () => {
  const [filters, setFilters] = useState({ search: '', make: '', minPrice: '', maxPrice: '', fuel_type: '', transmission: '', body_style: '', zip: '', radius: '', lat: '', lng: '', sortBy: 'newest', page: 1 });
  const { cars, loading, error, totalPages } = useCars(filters, filters.page);
  const [featured, setFeatured] = useState(null);
  const [budgetCars, setBudgetCars] = useState([]);
  const [recommended, setRecommended] = useState([]);
  const [view, setView] = useState(localStorage.getItem('autovault-view') || 'grid');
  const switchView = (v) => { setView(v); localStorage.setItem('autovault-view', v); };
  useEffect(() => { getCarById(7).then(r => setFeatured(r.data)).catch(() => {}); }, []);
  useEffect(() => { getCars({ maxPrice: 10000, sortBy: 'price_asc', limit: 12 }).then(r => setBudgetCars(r.data.cars)).catch(() => {}); }, []);
  useEffect(() => { getCars({ sortBy: 'newest', limit: 6 }).then(r => setRecommended(r.data.cars)).catch(() => {}); }, []);
  const handlePage = (p) => { setFilters(f => ({...f, page: p})); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  return <div className="browse-page">{featured && <div className="featured-section"><Link to={`/cars/${featured.id}`} className="featured-card"><div className="featured-image"><img src={featured.images?.[0]?.url || featured.main_image} alt={`${featured.year} ${featured.make} ${featured.model}`} /><span className="featured-badge">Featured</span></div><div className="featured-info"><h2>{featured.year} {featured.make} {featured.model}</h2><p className="featured-trim">{featured.trim}</p><p className="featured-price">{fmtPrice(featured.price)}</p><p className="featured-desc">{featured.description}</p><span className="featured-link">View Details →</span></div></Link></div>}{recommended.length > 0 && <div className="recommended-section"><h2 className="section-heading">Recommended for You</h2><div className="recommended-scroll">{recommended.map(car => <Link key={car.id} to={`/cars/${car.id}`} className="recommended-card"><div className="recommended-img"><img src={car.main_image} alt={`${car.year} ${car.make} ${car.model}`} /></div><div className="recommended-info"><h3>{car.year} {car.make} {car.model}</h3><p className="recommended-price">{fmtPrice(car.price)}</p></div></Link>)}</div></div>}{budgetCars.length > 0 && <div className="budget-section"><h2 className="section-heading">Budget Buys Under $10,000</h2><div className="budget-grid">{budgetCars.map(car => <Link key={car.id} to={`/cars/${car.id}`} className="budget-card"><div className="budget-img"><img src={car.main_image} alt={`${car.year} ${car.make} ${car.model}`} /></div><div className="budget-info"><h3>{car.year} {car.make} {car.model}</h3><p className="budget-trim">{car.trim}</p><p className="budget-price">{fmtPrice(car.price)}</p><p className="budget-meta">{car.mileage?.toLocaleString()} mi · {car.transmission}</p></div></Link>)}</div></div>}<div className="browse-header"><h1>Find Your Next Car</h1><Link to="/sell" className="sell-cta">List Your Car</Link><CarFilters filters={filters} onChange={setFilters} /></div><div className="view-toggle"><button className={view === 'grid' ? 'active' : ''} onClick={() => switchView('grid')}>Grid</button><button className={view === 'list' ? 'active' : ''} onClick={() => switchView('list')}>List</button></div>{loading ? <div className="spinner">Loading...</div> : error ? <div className="error">{error}</div> : cars.length === 0 ? <div className="no-results"><h2>No cars found</h2><p>Try adjusting your filters or <Link to="/sell">list your car</Link></p></div> : <><div className={view === 'grid' ? 'car-grid' : 'car-list'}>{cars.map(car => <CarCard key={car.id} car={car} />)}</div><Pagination currentPage={filters.page} totalPages={totalPages} onPageChange={handlePage} /></>}</div>;
};
export default BrowsePage;
