import MakeSelect, { MAKES } from './MakeSelect';
const FUEL_TYPES = ['Gasoline','Diesel','Hybrid','Electric'];
const TRANSMISSIONS = ['Automatic','Manual','CVT'];
const BODY_STYLES = ['SUV','Sedan','Coupe','Convertible','Hatchback','Truck','Van','Wagon'];
const SORT_OPTIONS = [['newest','Newest'],['price_asc','Price: Low to High'],['price_desc','Price: High to Low'],['year_desc','Year: Newest'],['year_asc','Year: Oldest'],['mileage_asc','Mileage: Low to High']];
const CarFilters = ({ filters, onChange }) => {
  const set = (key, value) => onChange({ ...filters, [key]: value, page: 1 });
  const clear = () => onChange({ search: '', make: '', minPrice: '', maxPrice: '', fuel_type: '', transmission: '', body_style: '', sortBy: 'newest', page: 1 });
  const hasFilters = filters.search || filters.make || filters.minPrice || filters.maxPrice || filters.fuel_type || filters.transmission || filters.body_style;
  return <div className="car-filters"><div className="search-bar"><input type="text" placeholder="Search make, model, or keyword..." value={filters.search} onChange={e => set('search', e.target.value)} /><select value={filters.sortBy} onChange={e => set('sortBy', e.target.value)}>{SORT_OPTIONS.map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></div><div className="filter-grid"><div className="make-filter-cell"><MakeSelect value={filters.make} onChange={v => set('make', v)} placeholder="All Makes" /></div><select value={filters.fuel_type} onChange={e => set('fuel_type', e.target.value)}><option value="">All Fuel Types</option>{FUEL_TYPES.map(f => <option key={f} value={f}>{f}</option>)}</select><select value={filters.transmission} onChange={e => set('transmission', e.target.value)}><option value="">All Transmissions</option>{TRANSMISSIONS.map(t => <option key={t} value={t}>{t}</option>)}</select><select value={filters.body_style} onChange={e => set('body_style', e.target.value)}><option value="">All Body Styles</option>{BODY_STYLES.map(b => <option key={b} value={b}>{b}</option>)}</select><input type="number" placeholder="Min Price" value={filters.minPrice} onChange={e => set('minPrice', e.target.value)} /><input type="number" placeholder="Max Price" value={filters.maxPrice} onChange={e => set('maxPrice', e.target.value)} /></div>{hasFilters && <button className="clear-filters" onClick={clear}>Clear Filters</button>}</div>;
};
export default CarFilters;
