import { BrowserRouter, Routes, Route } from 'react-router-dom';
import { AuthProvider } from './context/AuthContext';
import Navbar from './components/Navbar';
import Footer from './components/Footer';
import ProtectedRoute from './components/ProtectedRoute';
import VehiclePage from './pages/VehiclePage';
import LaunchPage from './pages/LaunchPage';
import TermsPage from './pages/TermsPage';
import BudgetPage from './pages/BudgetPage';
import Login from './pages/Login';
import Register from './pages/Register';
import CarDetail from './pages/CarDetail';
import EditCar from './pages/EditCar';
import MyListings from './pages/MyListings';
import SellCar from './pages/SellCar';
import Checkout from './pages/Checkout';
import OrderSuccess from './pages/OrderSuccess';
import Messages from './pages/Messages';
import AdminDashboard from './pages/AdminDashboard';
import PlatesBrowse from './pages/PlatesBrowse';
import PlateDetail from './pages/PlateDetail';
import SellPlate from './pages/SellPlate';
import Advertise from './pages/Advertise';
const App = () => <AuthProvider><BrowserRouter><Navbar /><Routes><Route path="/advertise" element={<Advertise />} /><Route path="/launch" element={<LaunchPage />} /><Route path="/terms" element={<TermsPage />} /><Route path="/" element={<VehiclePage />} /><Route path="/budget/:amount" element={<BudgetPage />} /><Route path="/login" element={<Login />} /><Route path="/register" element={<Register />} /><Route path="/cars/:id" element={<CarDetail />} /><Route path="/sell" element={<ProtectedRoute><SellCar /></ProtectedRoute>} /><Route path="/cars/:id/edit" element={<ProtectedRoute><EditCar /></ProtectedRoute>} /><Route path="/my-listings" element={<ProtectedRoute><MyListings /></ProtectedRoute>} /><Route path="/checkout/:id" element={<ProtectedRoute><Checkout /></ProtectedRoute>} /><Route path="/order-success" element={<ProtectedRoute><OrderSuccess /></ProtectedRoute>} /><Route path="/messages" element={<ProtectedRoute><Messages /></ProtectedRoute>} /><Route path="/admin" element={<ProtectedRoute adminOnly><AdminDashboard /></ProtectedRoute>} /><Route path="/plates" element={<PlatesBrowse />} /><Route path="/plates/:id" element={<PlateDetail />} /><Route path="/plates/sell" element={<ProtectedRoute><SellPlate /></ProtectedRoute>} /></Routes><Footer /></BrowserRouter></AuthProvider>;
export default App;
